
services:
  nginx:
    build: docker/nginx
    container_name: morele-nginx
    working_dir: /var/www/application
    volumes:
      - .:/var/www/application
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    depends_on:
      - php-fpm

  php-fpm:
    build: docker/php-fpm
    container_name: morele-php
    working_dir: /var/www/application
    environment:
      PS1: "php@morele:$$PWD\\$ "
    volumes:
      - .:/var/www/application
      - ./docker/php-fpm-fpm/php-fpm-ini-overrides.ini:/etc/php-fpm/7.4/fpm/conf.d/99-overrides.ini